name: Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:
    
jobs:

  test_environment_secret1:
    runs-on: ubuntu-latest
    environment: test1
    - name: Run tests
      run: |
        echo "user=${{ secret.user }}" | tee -a "$GITHUB_OUTPUT"

  test_environment_secret1:
    runs-on: ubuntu-latest
    environment: test2
    - name: Run tests
      run: |
        echo "user=${{ secret.user }}" | tee -a "$GITHUB_OUTPUT"
