name: Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      docker_registry:
        description: Docker registry
        required: true
        default: 'quay.io'
        type: choice
        options:
          - 'quay.io'
          - 'quay.io'
      registry_org:
        description: Docker registry organisation
        required: true
        default: 'ministryofjustice'
        type: choice
        options:
          - 'ministryofjustice'
          - 'hmpps'
      additional_docker_tag:
        description: Additional docker tag that can be used to specify stable  tags
        required: false
        default: ''
        type: string
      push:
        description: Push docker image to registry flag
        required: true
        default: true
        type: boolean

permissions:
  contents: read
  packages: write
  
jobs:

  test_multiplatform_docker_build:
    name: Build docker image from hmpps-github-actions
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/build_multiplatform_docker.yml@feat/HEAT-344-share-app-version-across-jobs
    secrets: inherit
    with:
      docker_registry: ${{ inputs.docker_registry || 'quay.io' }}
      registry_org: ${{ inputs.registry_org || 'hmpps' }}
      additional_docker_tag: ${{ inputs.additional_docker_tag }}
      push: ${{ inputs.push || true }}

